### ISSUE TITLE
Not able to launch noVNC anymore

### ISSUE THREAD

**Issue by jankeromnes** [novnc/noVNC#769]
I'm no longer able to launch noVNC the way I did before.

The command `bash /home/user/.novnc/utils/launch.sh --vnc localhost:5900 --listen 8089` now fails instantly with the following error log:

```
Warning: could not find self.pem
Using local websockify at /home/user/.novnc/utils/websockify/run
Starting webserver and WebSockets proxy on port 8089
/home/user/.novnc/utils/websockify/websockify/websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
Traceback (most recent call last):
  File "/home/user/.novnc/utils/websockify/run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "/home/user/.novnc/utils/websockify/websockify/websocketproxy.py", line 536, in websockify_init
    server = WebSocketProxy(**opts.__dict__)
  File "/home/user/.novnc/utils/websockify/websockify/websocketproxy.py", line 277, in __init__
    websockifyserver.WebSockifyServer.__init__(self, RequestHandlerClass, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'auto_pong'
Failed to start WebSockets proxy
```

**Comment by jankeromnes** [comment]
The bug seems to have been introduced by https://github.com/novnc/websockify/commit/8a697622495fd319582cd1c604e7eb2cc0ac0ef6 (see associated websockify issue).

**Comment by CendioOssman** [comment]
Handled on novnc/websockify#264.
